#! /bin/bash
exec < /dev/tty #allows stdin for hooks
read -p "Back up test database to mysql/gb_test.sql? [yN] " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]; then
   echo "moving test db dump to .old..."
   mv ./mysql/gb_test.sql ./mysql/gb_test.sql.old #in case a mistake was made
   echo "creating new test db dump..."
   mysqldump -u testroot -ppass gb_test > ./mysql/gb_test.sql
   git add ./mysql/gb_test.sql
fi
